export const CAMPAIGN_STATUS = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  ENDED: "ENDED",
};

export const CAMPAIGN_TYPES = {
  USER: "USER",
  INFLUENCER: "INFLUENCER",
};

export const CAMPAIGN_PARTICIPANT_STATUS = {
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  REMOVED: "REMOVED",
};

export const CAMPAIGN_PARTICIPANT_TYPE = {
  USER: "USER",
  INFLUENCER: "INFLUENCER",
  VIP_INFLUENCER: "VIP_INFLUENCER",
};

export const REWARD_TYPES = {
  COINS: "COINS",
  CASH: "CASH",
};

export const COMMISSION_PERCENTAGE = 0.2; 
