export const REFERRAL_TYPES = {
  USER: "USER", 
  INFLUENCER: "INFLUENCER",
};

export const REFERRAL_STATUS = {
  PENDING: "PENDING",
  QUALIFIED: "QUALIFIED",
  REWARDED: "REWARDED",
  REJECTED: "REJECTED",
};

export const REFERRAL_SOURCE = {
  DIRECT_LINK: "DIRECT_LINK",
  INSTAGRAM: "INSTAGRAM",
  TIKTOK: "TIKTOK",
  WHATSAPP: "WHATSAPP",
  FACEBOOK: "FACEBOOK",
  QR_CODE: "QR_CODE",
  DEEPLINK: "DEEPLINK",
  UNKNOWN: "UNKNOWN",
};

export const REWARD_TYPES = {
  COINS: "COINS",
  CASH: "CASH",
};

export const REFERRAL_REWARD_AMOUNT = {
  USER: 15,
  INFLUENCER: 0,
};
