export const INFLUENCER_STATUS = {
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  REMOVED: "REMOVED",
};

export const EARNING_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  PAID: "PAID",
  FAILED: "FAILED",
};

export const REFERRAL_STATUS = {
  PENDING: "PENDING",
  QUALIFIED: "QUALIFIED",
  REWARDED: "REWARDED",
};

export const COMMISSION_PERCENTAGE = 0.2; // 20%
