import {
  NOTIFICATION_TYPES,
  NOTIFICATION_CHANNELS,
} from "./notification.constants.js";

export const NOTIFICATION_CHANNEL_POLICIES = {
  [NOTIFICATION_TYPES.CONNECTION_REQUEST_RECEIVED]: [
    NOTIFICATION_CHANNELS.IN_APP,
    NOTIFICATION_CHANNELS.EMAIL,
  ],

  [NOTIFICATION_TYPES.CONNECTION_REQUEST_ACCEPTED]: [
    NOTIFICATION_CHANNELS.IN_APP,
    NOTIFICATION_CHANNELS.EMAIL,
  ],

  [NOTIFICATION_TYPES.NEW_MATCH]: [
    NOTIFICATION_CHANNELS.IN_APP,
    NOTIFICATION_CHANNELS.EMAIL,
    NOTIFICATION_CHANNELS.WHATSAPP,
  ],

  [NOTIFICATION_TYPES.NEW_MESSAGE]: [NOTIFICATION_CHANNELS.IN_APP],

  [NOTIFICATION_TYPES.STAGE_UNLOCKED]: [NOTIFICATION_CHANNELS.IN_APP],

  [NOTIFICATION_TYPES.PROFILE_VIEWED]: [NOTIFICATION_CHANNELS.IN_APP],

  [NOTIFICATION_TYPES.COINS_AWARDED]: [NOTIFICATION_CHANNELS.IN_APP],

  [NOTIFICATION_TYPES.COIN_PURCHASE_COMPLETED]: [
    NOTIFICATION_CHANNELS.IN_APP,
    NOTIFICATION_CHANNELS.EMAIL,
  ],

  [NOTIFICATION_TYPES.REFERRAL_REWARDED]: [
    NOTIFICATION_CHANNELS.IN_APP,
    NOTIFICATION_CHANNELS.EMAIL,
  ],

  [NOTIFICATION_TYPES.SYSTEM]: [NOTIFICATION_CHANNELS.IN_APP],
};
